### ISSUE TITLE
would have been cool if background-image on template page would be global public object instead of inline base64 image data :)

### ISSUE THREAD

**Issue by subscribernamegoeshere** [maidsafe/safe_launcher#101]
would have been cool if background-image on template page would be global public object instead of inline base64 image data :)

html source of generated template page in the demo has inline base64 background-image image/jpeg data.

would have been a nice aspect of the demo if that image would have been coming from a globally public ID address on .safenet itself

comparing/benchmarking such a global public object for everybody and its spread and latency and all

**Comment by krishnaIndia** [comment]
Thanks for your feedback. We will certainly update in the next version of the demo app. This issue is related to the demo app. Created the [same issue in safe_examples](https://github.com/maidsafe/safe_examples/issues/50) repo. Closing this issue here.
