### ISSUE TITLE
Build failure on OSX

### ISSUE THREAD

**Issue by skaag** [maidsafe/safe_launcher#105]
```
/Users/skaag/.cargo/registry/src/github.com-0a35038f75765ae4/temp_utp-0.7.2/src/socket.rs:522:34: 522:46 error: use of unstable library feature 'drain': recently added, matches RFC (see issue #27711)
/Users/skaag/.cargo/registry/src/github.com-0a35038f75765ae4/temp_utp-0.7.2/src/socket.rs:522             self.read_ready_data.drain(..len);
                                                                                                                               ^~~~~~~~~~~~
```

Versions of libraries/binaries:

- libsodium 1.8.0
- rustc 1.5.0 (3d7cd77e4 2015-12-04)
- cargo 0.6.0-nightly (e1ed995 2015-10-22)

**Comment by dirvine** [comment]
Are you using latest stable (1.6) as drain was stabilized then.

On Wed, Mar 2, 2016 at 12:31 AM, Skaag Argonius <notifications@github.com>
wrote:

> /Users/skaag/.cargo/registry/src/github.com-0a35038f75765ae4/temp_utp-0.7.2/src/socket.rs:522:34: 522:46 error: use of unstable library feature 'drain': recently added, matches RFC (see issue #27711)
> /Users/skaag/.cargo/registry/src/github.com-0a35038f75765ae4/temp_utp-0.7.2/src/socket.rs:522             self.read_ready_data.drain(..len);
>                                                                                                                                ^~~~~~~~~~~~
>
> Versions of libraries/binaries:
>
>    - libsodium 1.8.0
>    - rustc 1.5.0 (3d7cd77e4 2015-12-04)
>    - cargo 0.6.0-nightly (e1ed995 2015-10-22)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maidsafe/safe_launcher/issues/105>.
>



-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by skaag** [comment]
Latest stable of what? do you mean `rustc`?

**Comment by dirvine** [comment]
Yes rustc, a lot of us use multirust (very easy to switch/upgrade etc.) You should try it out, makes life in rust much simpler as well.

**Comment by skaag** [comment]
Will do that and report back. looks like the OSX brew uninstall process for `rust` and `Caskroom/cask/rust` are not very clean and leave behind various artifacts... :-1:

**Comment by dirvine** [comment]
That's good, if you can let us know it will be great. Thanks

**Comment by skaag** [comment]
Ok, first of all, thank you for the multirust tip. That was awesome! I am now using rustc 1.6.0 (stable) and the compilation process proceeded much further along.

It still fails though:
```
   Compiling safe_core v0.5.0
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:37:5: 56:6 error: method `get` has an incompatible type for trait:
 expected &-ptr,
    found struct `collections::vec::Vec` [E0053]
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:37     fn get(&self, name: Vec<u8>) -> Vec<u8> {
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:38         let mut name_id = [0u8; 64];
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:39         assert_eq!(name.len(), 64);
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:40         for i in 0..64 {
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:41             name_id[i] = name[i];
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:42         }
                                                                                                                                           ...
/Users/skaag/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.5.0/src/self_encryption_storage.rs:37:5: 56:6 help: run `rustc --explain E0053` to see a detailed explanation
error: aborting due to previous error
Could not compile `safe_core`.
```

**Comment by skaag** [comment]
ping

**Comment by dirvine** [comment]
:+1
