### ISSUE TITLE
OSX: "safe_launcher" can't be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by hems** [maidsafe/safe_launcher#106]
I'm sure you guys are aware of that problem and that most users are aware that they must right-click and then left-click "Open", but it's always worth to have this issue open, so some people will find the solution and you guys will remember this little annoying detail.

<img width="420" alt="screen shot 2016-03-02 at 01 19 23" src="https://cloud.githubusercontent.com/assets/27327/13447619/ebbb0392-e014-11e5-8517-7f14f4296ffd.png">

**Comment by krishnaIndia** [comment]
Thanks for reporting the issue @hems. We will definitely sign the binaries when we get to the installers. Until then, this would be a limitation. If you agree, can we close this issue?

**Comment by hems** [comment]
sure! anyway i don't think a installer is needed for OSX?
