### ISSUE TITLE
Possibility to configure safe proxy port

### ISSUE THREAD

**Issue by ligthyear** [maidsafe/safe_launcher#119]
Heyah,

running safe launcher stable and development at the same time is currently not possible as they both decide to the same _fixed_ port for offering proxying through the network. It'd be nice if we could configure the port to be used (at least for the development version) manually.

**Comment by krishnaIndia** [comment]
You can use the [config](https://github.com/maidsafe/safe_launcher/blob/master/config/env_development.json#L4) to change the port. Closing this issue as we already have the option provided.

Thanks @ligthyear
