### ISSUE TITLE
libsafe_ffi.so: undefined symbol: sodium_increment

### ISSUE THREAD

**Issue by npmstart-pray** [maidsafe/safe_launcher#125]
has anyone run into this:

Ffi load error [Error: Dynamic Linking Error: /home/greg/safe_launcher/build/api/ffi/libsafe_ffi.so: undefined symbol: sodium_increment]
?

**Comment by krishnaIndia** [comment]
Please try the v0.6.0, this should be fixed. If you still face the same problem, please do re-open this issue. Thanks @npmstart-pray
