### ISSUE TITLE
Error on multiple file upload

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#130]
Multiple file upload ended with an error suggested by launcher terminal.

maidsafe_demo_app lost contact with launcher and did the stable complaint that launcher should always be running. Launcher looked open but terminal suggested an error.

Error then from safe_launcher-v0.4.3-linux-x64 on Linux Mint 17.3 Rosa
```
thread '<unnamed>' panicked at '

 ====================================================================================================
| Result evaluated to Err: CoreError::MutationFailure::{ reason: LowBalance, data: ImmutableData e574..} |
 ====================================================================================================

', /home/viv/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.14.4/src/core/self_encryption_storage.rs:59
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at '

 ======================================================
| Result evaluated to Err: "PoisonError { inner: .. }" |
 ======================================================

', /home/viv/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/safe_core-0.14.4/src/core/self_encryption_storage.rs:59
```

**Comment by davidpbrown** [comment]
I did again with RUST_BACKTRACE=1 but it wasn't obvious what additional detail that provides.. looked same as above. Unclear what the trigger is but it seems not a full directory uploaded and less than 100MB.

Another attempt suggested a file failed to upload but then testing that file was fine. I don't think that will be the issue behind this though.

**Comment by davidpbrown** [comment]
I see now client size is much smaller, so perhaps that's the cause but still is a frequent enough issue that needs to be considered.

Close if not useful..

**Comment by krishnaIndia** [comment]
This error should be fixed by now @davidpbrown. The logs were helpful to get the issue fixed. Thank you
