### ISSUE TITLE
Safe Launcher doesn't connect

### ISSUE THREAD

**Issue by NateHerman** [maidsafe/safe_launcher#131]
Hi.  Safe Vault works fine.

When I go to create an account, upon entering the PIN twice & clicking "next", get an error:  "Waiting for establishing connection with safe network"

Win 8, 64-bit machine.

**Comment by PedroSwift** [comment]
On Mac 0SX, experiencing exactly the same. "Waiting for establishing connection with safe network".  Just sits there.

**Comment by CaptainSkywave** [comment]
same issue here
![create](https://cloud.githubusercontent.com/assets/8870171/15096543/bda26aea-14fd-11e6-870b-eb7f842b761b.png)

**Comment by theWebalyst** [comment]
Are you all aware that the test has finished, or are these reports from the short period during which the test was running?

**Comment by CaptainSkywave** [comment]
oohhh - was not aware - yes trying right now, so gonna stop it then :)

**Comment by PedroSwift** [comment]
So, we're not supposed to be testing at the moment?

**Comment by NickLambert** [comment]
That's correct, testing has finished for now @PedroSwift.

**Comment by theWebalyst** [comment]
Another test might follow quite soon - maybe this week. Watch the forum/twitter for announcements if you'd like to take part.

**Comment by dirvine** [comment]
Yes these iterations will increase in ferocity now, for the very short term anyway.

**Comment by PedroSwift** [comment]
@dirvine OK David, I'll try to keep up :) Time zones may make that difficult.

**Comment by NateHerman** [comment]
Cool. Wasn't aware the test was over. Thanks for the heads up; I'll check
next time I post a bug. Peace, n8
