### ISSUE TITLE
Linux ffi launcher crash after running a long while

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#133]
Launcher had been running ?~2hours unattended. Got a popup ffi error that I hadn't seen before and didn't take note of as I think others with Windows had the same but in the terminal was a new error type that I'll note here in case it's useful:
```
/home/davidpbrown/SAFE/safe_launcher-v0.4.3-linux-x64/resources/app.asar/node_modules/ffi/lib/callback.js:18
        throw new Error(err)
        ^

Error: ffi fatal: callback has been garbage collected!
    at /home/davidpbrown/SAFE/safe_launcher-v0.4.3-linux-x64/resources/app.asar/node_modules/ffi/lib/callback.js:18:15
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

**Comment by chrisfoster** [comment]
Also had this happen on Win7 after a long run with no issues.

'FFI process terminated'

**Comment by krishnaIndia** [comment]
The FFI callback garbage collection is handled in v0,6,0. Please do re-poen if the issue persists. Thanks @chrisfoster & @davidpbrown
