### ISSUE TITLE
Launcher fails after ...?

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_launcher#135]
Transferred from https://maidsafe.atlassian.net/projects/CS/issues/CS-42?filter=allopenissues

> "Debian Jesse... with 8th March launcher and demo.
> 
> Everything was snappier and worked well up to a point. As soon as I registered an account I could browse the first uploaded websites, and I began uploading a large website: http://safepress.safenet/
> 
> The website was slow but steady to upload, and completed, and unlike testnet1, the service was listed immediately the download comleted. The upload probably took 20 minutes.
> 
> When I tried to visit the link http://safepress.safenet/ it timed out without displaying anything or any errors in browser, demo app or launcher.
> 
> I tried to view the uploaded files in the launcher but it sat there showing the wait GIF.
> 
> I killed the demo app and started a new one. It said initialising but the launcher didn't prompt me to authorise.
> 
> I tried browsing a SAFE website that was working previously, and it failed without error.
> 
> I restarted the launcher, logged in, and could visit http://safepress.safenet/ successfully. So it looks like after one upload (or a period of 20 minutes or so) the launcher failed.
> 
> I began writing up this issue (delay of 10 mins or so) and then...
> 
> ...started a new demo app and was able to "Allow" in the launcher, but now both launcher and demo app appear stuck again indefinitely. Demo app says "waiting for response", and launcher shows the activity GIF (rotating circle)."
> 
> "Thanks Mark - we have a few reports of the Launcher disconnecting or hanging after x minutes - I will try and replicate this issue.
> Thank you
> Ross"
> 
> "Hi Mark,
> 
> Using the new release > https://forum.safenetwork.io/t/safe-launcher-v0-4-1-patch-update-released/8166 - I have observed no disconnecting or hanging.
> 
> If you have some time to test this out can you provide feedback please?
> 
> Thanks
> Ross"
> 
> 
> "Hi Mark,
> 
> Brief update - spoke too soon - have experienced some intermittent hanging.
> 
> Thanks
> Ross"

**Comment by rossmuir** [comment]
Transferring > https://maidsafe.atlassian.net/projects/CS/issues/CS-54?filter=allopenissues with similar behaviour.

> "Safe Launcher v0.4.0
> Maidsafe Demo App v0.2.1
> OS: Windows 10 64 through VirtualBox
> ------------------------------------------------------------------------------
> 
> Dear Maidsafe team,
> 
> The following issue has been replicated 3 times out of 3 tests.
> 
> 1. Start the launcher and login,
> 2. Start the demo app, allow it in the launcher, and download a private file, just to confirm you are indeed connected.
> 3. Close the demo app, but keep the launcher opened in the background,
> 4. Wait 40 minutes,
> 5. Launch the demo app once again.
> 
> > The demo app stays on the screen "initialising" (Capture1.png) for 4 minutes, and then displays the "could not connect to the network" error (Capture2.png)
> Any further attempt to relaunch the demo app yields the same results, unless I first close the launcher, restart it, and then log in again to the network.
> 
> I was expecting that the launcher would maintain the connection as long as it is started, and if internet connection is lost then tries to reconnect"

**Comment by davidpbrown** [comment]
This was occurring after a relatively short while in Testnet3 @~22:00BST.
and you can skip Step 4 waiting 40mins is not necessary, I was doing it immediately.

Unclear if it's an effect of having had the Demo app open once and closed it.

When I could login on a established account, the Demo app would not complete initialising but that might have been a network issue - so anyway I closed it and restarting it experienced the same as above and then I also couldn't view safenet sites, where I had been able to up to that point. No indication of a problem from the Launcher itself or its terminal. The Demo app eventually complained that it could be see the Launcher and that should be left running.. though it was still open.

So, I wonder this is an issue with Demo app instance 2+ interacting with the Launcher. Curious that it then stops the Launcher working as proxy for the browsing of sites too.

The Launcher initially suggests its connection status but it doesn't update an indicator and knowing that the proxy is working ok might be useful; it's currently left for the application trying to use that to indicate a problem - which for the browser isn't always obvious.

**Comment by krishnaIndia** [comment]
The launcher seems to be stable with [v0,6](https://github.com/maidsafe/safe_launcher/releases/tag/0.6.0). Please do re-open this issue, if you face similar problem with the latest version
