### ISSUE TITLE
account details keep getting deleted/lost

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/safe_launcher#140]
Okay this is the third or fourth time this has happened to me.  I deliberately made a very routine, simple and easy to remember account name, password and pin so there would be no chance in hell I'd forget it.   So I create the account, log in, log off, and can't log in again.   I now have 3 or 4 accounts that have been lost this way (and 3 or 4 public ids that are recorded by the system that I can no longer use which is even MORE annoying).   I'm not sure if this is a demo app issue, launcher issue or vault issue.   Forgive me if this gets misfiled.   But given this issue is cropping up under log in creds I'm filing it under the launcher.   I get that vaults are buggy right now.  I get that we expect data loss.   But EVERY TIME I try and create an account?   How am I to upload anything if I can't log back into my account?

**Comment by krishnaIndia** [comment]
Thanks @Blindsite, we will try to fix this issue sooner.

**Comment by Blindsite** [comment]
Thanks.   If you can it would be helpful to some way bind one's public ID to one's account somehow so that if one's account gets deleted that one's public Id goes with it.   It's very frustrating to keep creating accounts, even the same log in credentials, and have to use different public Ids.   Of course this might become a moot point in future with the release of safecoin and SD.

**Comment by krishnaIndia** [comment]
Sorry @Blindsite, this seems to be a known limitation as stated in the [thread](https://forum.safenetwork.io/t/maidsafe-dev-update-17th-may-2016-test-3-update-20th-may-13-30-bst-now-complete/9273).
