### ISSUE TITLE
v0.4.5 Launcher API accepts requests from unnamed apps

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#144]
Using the example tests for the API from https://github.com/wrnice/rsafe it's apparent that the launcher will accept whitespace in the header request fields to authorise an app.

So, while empty fields are challenged, this does work:
```
	let appdetails = auth::AppDetails {
		name: " ".to_string(),
		version: " ".to_string(),
		vendor: " ".to_string(),
		id: " ".to_string(),
		permissions: vec! []
	};	
```

Broader questions then arise about the risk of another malicious app adopting some name the user recognises.. like Vendor = Maidsafe. That field alone challenges the user that Authorisation Request by Maidsafe, which naive users would accept. I don't know what can be done to validate applications but ensuring they declare all fields is a start.

**Comment by krishnaIndia** [comment]
Thanks @davidpbrown. This should be resolved in [v0.6.0](https://github.com/maidsafe/safe_launcher/releases/tag/0.6.0).
