### ISSUE TITLE
Unable to Register

### ISSUE THREAD

**Issue by PaulDStevenson** [maidsafe/safe_launcher#151]
This is using Launcher v0.4.6. I get an 'Error in Registration' message whenever I attempt to register. 

Edit: I'm running Linux (Gnome Ubuntu 16.04).

Here are the logs (I tried twice).

DEBUG 20:52:19.526918969 [crust::main::service service.rs:552] Network name: Some("2016_06_14_test_network_4")
DEBUG 20:54:28.105877125 [crust::main::active_connection active_connection.rs:57] Entered state ActiveConnection: PeerId(0f57..) -> PeerId(4587..)
DEBUG 20:54:28.106064478 [routing::core core.rs:550] Disconnected(e5df77..) Received BootstrapConnect from PeerId(4587..).
DEBUG 20:54:28.106093781 [routing::core core.rs:1063] Disconnected(e5df77..) - Sending ClientIdentify to PeerId(4587..).
DEBUG 20:54:28.157705083 [routing::core core.rs:1276] Client(e5df77..) - State changed to client, quorum size: 5.
DEBUG 20:55:27.530950146 [crust::main::service service.rs:552] Network name: Some("2016_06_14_test_network_4")
DEBUG 20:57:35.995992833 [crust::main::active_connection active_connection.rs:57] Entered state ActiveConnection: PeerId(0461..) -> PeerId(558d..)
DEBUG 20:57:35.996100272 [routing::core core.rs:550] Disconnected(119e2e..) Received BootstrapConnect from PeerId(558d..).
DEBUG 20:57:35.996107985 [routing::core core.rs:1063] Disconnected(119e2e..) - Sending ClientIdentify to PeerId(558d..).
DEBUG 20:57:36.041791847 [routing::core core.rs:1276] Client(119e2e..) - State changed to client, quorum size: 5.
DEBUG 20:57:36.739630360 [safe_core::nfs::helper::directory_helper directory_helper.rs:195] Retrieving root directory ...
DEBUG 20:57:36.739821209 [safe_core::nfs::helper::directory_helper directory_helper.rs:75] Posting PUT request to network to save structured data for directory ...
DEBUG 20:57:38.626913950 [safe_core::nfs::helper::directory_helper directory_helper.rs:75] Posting PUT request to network to save structured data for directory ...
DEBUG 20:57:39.701960433 [safe_core::nfs::directory_listing mod.rs:187] Adding metadata to directory listing ...
DEBUG 20:57:39.702183451 [safe_core::nfs::helper::directory_helper directory_helper.rs:374] Getting structured data from the network ...
DEBUG 20:57:40.138867708 [safe_core::nfs::helper::directory_helper directory_helper.rs:354] Posting updated structured data to the network ...
DEBUG 20:59:19.505932540 [crust::main::service service.rs:552] Network name: Some("2016_06_14_test_network_4")
DEBUG 21:01:28.063908299 [crust::main::active_connection active_connection.rs:57] Entered state ActiveConnection: PeerId(8396..) -> PeerId(6f78..)
DEBUG 21:01:28.064072060 [routing::core core.rs:550] Disconnected(d08da5..) Received BootstrapConnect from PeerId(6f78..).
DEBUG 21:01:28.064220783 [routing::core core.rs:1063] Disconnected(d08da5..) - Sending ClientIdentify to PeerId(6f78..).
DEBUG 21:01:28.127001810 [routing::core core.rs:1276] Client(d08da5..) - State changed to client, quorum size: 5.
DEBUG 21:01:31.239534977 [safe_core::nfs::helper::directory_helper directory_helper.rs:195] Retrieving root directory ...
DEBUG 21:01:31.239959742 [safe_core::nfs::helper::directory_helper directory_helper.rs:75] Posting PUT request to network to save structured data for directory ...
DEBUG 21:01:33.390668073 [safe_core::nfs::helper::directory_helper directory_helper.rs:75] Posting PUT request to network to save structured data for directory ...
DEBUG 21:01:35.111146486 [safe_core::nfs::directory_listing mod.rs:187] Adding metadata to directory listing ...
DEBUG 21:01:35.111184862 [safe_core::nfs::helper::directory_helper directory_helper.rs:374] Getting structured data from the network ...
DEBUG 21:01:35.613386373 [safe_core::nfs::helper::directory_helper directory_helper.rs:354] Posting updated structured data to the network ...

{"level":"debug","message":"Starting FFI worker client","timestamp":"2016-06-14T19:52:19.411Z"}
{"level":"debug","message":"Sending FFI initialisation request","timestamp":"2016-06-14T19:52:19.419Z"}
{"level":"debug","message":"Sending message to FFI [object Object]","timestamp":"2016-06-14T19:52:19.419Z"}
{"level":"debug","message":"Message callback IDGjDr1GCe4tQntLLTr17+K8n07efJ9ICPlnaNpNfXZNANHRMPac4AJ7Hmqx58Wo4EyuSaTU6oJaJ9mdRi56Hw9A== [object Object]","timestamp":"2016-06-14T19:52:19.440Z"}
{"level":"debug","message":"Application starting","timestamp":"2016-06-14T19:52:19.443Z"}
{"level":"info","message":"Starting proxy server","timestamp":"2016-06-14T19:52:19.536Z"}
{"level":"debug","message":"Proxy Server - onMessage event - recieved - {\"status\":true,\"data\":\"Proxy Started\"}","timestamp":"2016-06-14T19:52:19.639Z"}
{"level":"info","message":"Proxy server started","timestamp":"2016-06-14T19:52:19.639Z"}
{"level":"debug","message":"FFI onmessage :: [object Object]","timestamp":"2016-06-14T19:54:28.163Z"}
{"level":"debug","message":"Network state change event recieved :: 0","timestamp":"2016-06-14T19:54:28.164Z"}
{"level":"info","message":"Connected with Network","timestamp":"2016-06-14T19:54:28.164Z"}
{"level":"debug","message":"Invoking Auth::resgister API","timestamp":"2016-06-14T19:55:27.518Z"}
{"level":"debug","message":"Sending message to FFI [object Object]","timestamp":"2016-06-14T19:55:27.519Z"}
{"level":"debug","message":"Message callback IDyMPeYvUml6LVM7HGVxGvZT/PpuGQ/xf6sQY/ImRg1I006+jd8qF+/E8m+IbtJea9RU8/sPOrJiLlDR8HaIcRTw== [object Object]","timestamp":"2016-06-14T19:55:27.523Z"}
{"level":"debug","message":"FFI onmessage :: [object Object]","timestamp":"2016-06-14T19:57:40.800Z"}
{"level":"debug","message":"invoking Response callback :: callback id - yMPeYvUml6LVM7HGVxGvZT/PpuGQ/xf6sQY/ImRg1I006+jd8qF+/E8m+IbtJea9RU8/sPOrJiLlDR8HaIcRTw==","timestamp":"2016-06-14T19:57:40.801Z"}
{"level":"debug","message":"Invoking Auth::resgister API","timestamp":"2016-06-14T19:59:19.497Z"}
{"level":"debug","message":"Sending message to FFI [object Object]","timestamp":"2016-06-14T19:59:19.498Z"}
{"level":"debug","message":"Message callback IDIakDGqtfYHoTDqaEf8II4FGu2rhe1RSiEggTMvlttqAxnPpxA/km5uAafkZIc18KYd6BTPjdQ1MsTk9xrK9jbw== [object Object]","timestamp":"2016-06-14T19:59:19.500Z"}
{"level":"debug","message":"FFI onmessage :: [object Object]","timestamp":"2016-06-14T20:01:36.233Z"}
{"level":"debug","message":"invoking Response callback :: callback id - IakDGqtfYHoTDqaEf8II4FGu2rhe1RSiEggTMvlttqAxnPpxA/km5uAafkZIc18KYd6BTPjdQ1MsTk9xrK9jbw==","timestamp":"2016-06-14T20:01:36.233Z"}

Note: I couldn't register on the stable droplet test network either (that was a week ago, using the other binaries).

**Comment by PaulDStevenson** [comment]
Tried again this morning. Same error. Here is the stdout/err:

$ ./safe_launcher 
/home/paul/Downloads/safe_launcher-v0.4.6-linux-x64/resources/app.asar/api/ffi/worker.js:15
    if (!handler) {
         ^

ReferenceError: handler is not defined
    at process.cleanUp (/home/paul/Downloads/safe_launcher-v0.4.6-linux-x64/resources/app.asar/api/ffi/worker.js:15:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
/home/paul/Downloads/safe_launcher-v0.4.6-linux-x64/resources/app.asar/api/ffi/worker.js:15
    if (!handler) {
         ^

ReferenceError: handler is not defined
    at process.cleanUp (/home/paul/Downloads/safe_launcher-v0.4.6-linux-x64/resources/app.asar/api/ffi/worker.js:15:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)

**Comment by PaulDStevenson** [comment]
I'm getting much more success with Test5 and was able to register on the first attempt.

**Comment by krishnaIndia** [comment]
Thanks @PaulDStevenson. Please do try [Test-6](https://forum.safenetwork.io/t/safe-network-test-6/10291/12) too :+1:
