### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by oceanicpanda** [maidsafe/safe_launcher#163]
System: Ubuntu 14.04.4 with apt-get update and upgrade run very recently. Minimal other software installed.

I've been having issues logging in to the launcher for the last 3-4 days but have only just found time to look more closely. I get the following error in terminal when I run the latest launcher binary and enter my login details:

ERROR 08:04:54.710784640 [safe_core::ffi mod.rs:262]

| FfiError::NfsError -> NfsError::CoreError -> No such dataCoreError::GetFailure::{ reason: NoSuchData, request: Structured(814508.., 15101)}

Vaults seem to be running fine (4 of them)
![launcher](https://cloud.githubusercontent.com/assets/13448316/16265715/374a920e-3881-11e6-80fb-557d31bb3e51.jpg)
![login](https://cloud.githubusercontent.com/assets/13448316/16265714/374698f2-3881-11e6-8a5c-c0eeb805e0db.jpg)
![registration](https://cloud.githubusercontent.com/assets/13448316/16265713/37466594-3881-11e6-8525-3792e23cc7d5.jpg)
![vaults](https://cloud.githubusercontent.com/assets/13448316/16265712/37446b68-3881-11e6-9386-085fd20c841e.jpg)

. The launcher says it's connected to the network. Best I can tell nothing changed on my side from the last time I connected to the first time I couldn't. I know without doubt my login details are correct. If I try to sign up again with the same details I get the following:

ERROR 08:24:33.812580515 [safe_core::ffi mod.rs:156]

| Data existsCoreError::MutationFailure::{ reason: DataExists, data_id: Structured(e843a5.., 0)}

Logs:

[Client.log.txt](https://github.com/maidsafe/safe_launcher/files/327736/Client.log.txt)

**Comment by krishnaIndia** [comment]
Should be resolved in the latest version, If you face the same problem please do re-open this issue
