### ISSUE TITLE
Error on start: Dynamic Symbol Retrieval Error

### ISSUE THREAD

**Issue by daviddahl** [maidsafe/safe_launcher#171]
Ffi load error [Error: Dynamic Symbol Retrieval Error: dlsym(0x7fbee350a7c0, drop_null_ptr): symbol not found]

I built `safe_core` like so: `cargo build --release --features use-mock-routing`

Log: https://0bin.net/paste/pLvHvfMU8CowyxYM#8S9umtT6baL7prFgbymkvDrHEYXc9kxGbERaZsYxfeJ

**Comment by daviddahl** [comment]
Also, I have the latest libsodium 1.0.10

**Comment by krishnaIndia** [comment]
The current master branch should have this fixed. Thanks @daviddahl
