### ISSUE TITLE
Accessing: http://localhost:8101/ kills the proxy

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_launcher#178]
So I was curious about how the proxy functions (and if I could do similar GETs via the api, without needing to use `/safenet` style APIs for sites), so I tried pinging `http://localhost:8101/` with the launcher active to see what's up.

I got an expected error message (`Only '.safenet' pages can be accessed`. But then the proxy/launcher / all sife sites fail to load after this. Including that same local launcher endpoint.

All you get is a standard chrome error. 

(On OSX el Cap, using chrome Version 51.0.2704.103 (64-bit))

Restarting the launcher repairs the network. Doing this again kills it.

**Comment by krishnaIndia** [comment]
I did notice this. The fix is ready and being tested along with few other
changes. Should be resolved and updated soon.

Thanks @joshuef

**Comment by joshuef** [comment]
Ha sweet. Rapid issue handling:D

 Thanks @krishnaIndia  !

Regarding GETs *not* via proxy. Is there some documentation for this already? (Does a version of this API exist?)

**Comment by krishnaIndia** [comment]
For the new api version, we are yet to update the documentation. This should happen in the next few days hopefully once the patch update with the fixes are out. 

But the old version document is hosted at [readme.io](https://maidsafe.readme.io/docs/auth) and the recent API changes in documented in the [RFC](https://github.com/maidsafe/rfcs/tree/master/text/0036-launcher-api-v0.5). Sorry for the inconvenience, the documentation will be updated soon.

**Comment by joshuef** [comment]
Not to worry. Thanks for pointing me in the right direction!
