### ISSUE TITLE
POST /auth 400 Bad request, 'fields are missing'

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_launcher#179]
I've followed the updated API specs here: https://github.com/maidsafe/rfcs/blob/master/text/0036-launcher-api-v0.5/0036-launcher-api-v0.5.md

And trying to mimic the demo app setup https://github.com/maidsafe/safe_examples/blob/master/demo_app/app/scripts/factories/safe_api_factory.js#L98-L114

But I cannot get the launcher to authorize a request.

I'm constantly receiving:
```json
{
"errorCode": 400,
"description": "Fields are missing"
}```

I'm trying to send, in the body:
```json
{
  app: {
    name: "tasdadasdasdadasdest",
    version: "testa",
    vendor:  "testb",
    id: "blablabla"
  },
  permissions: Array[]
}
```

Also something curious is that if I set headers to `application/json` I receive an error, but setting this, I don't.

I'm on OSX, el Cap, using chrome latest and either a node app or the simple API tester [DHC](https://dhc.restlet.com/) (as a chrome app) to ping the (latest 0.5.1) launcher API. But I'm getting nowhere (and probably missing something obvious).

Any ideas? (Also: Are there any logs created for the launcher? As it would be useful to know more than what's sent in the error to debug missing fields etc).

Thanks!

**Comment by krishnaIndia** [comment]
Hi @joshuef, are you trying to create a web app? If that is the case change the `host` to `api.safenet` instead of `localhost:8100`

This is a snippet which worked for me couple of days back :wink: 

```
var authPayload = {
    app: {
      id: 'com.samp-company.web',
      name: 'Safe Web Sample',
      vendor: 'Sample-Company',
      version: '0.1'
    },
    permissions: []
  };
  $.ajax({
      method: 'POST',
      url: 'http://api.safenet/auth',
      headers: {
        'content-type': 'application/json'
      },
      data: JSON.stringify(authPayload)
    })
    .done(function(response) {
      authToken = response.token;
      alert('Obtained Auth token');
    })
    .fail(function(res) {
      alert('Request Failed: \n status: ' + res.status + '\n Msg: ' + res.responseText);
    });
```

Let me know if you still face a problem please

**Comment by joshuef** [comment]
I'm actually trying to get a node/electron app going (node 6.2), so `api/safenet` gives errors (`403/forbidden` as expected).

This is the code i'm running:

```js
  const init = {

      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      data: JSON.stringify( 
      { 
        app: {
          id: 'com.samp-company.web',
          name: 'Safe Web Sample',
          vendor: 'Sample-Company',
          version: '0.1'
        },
        permissions: [] 
      }
    )
  }


  return fetch('http://localhost:8100/auth', init)
    .then((response) => {
      let parsedResponse
      if(response.status == 200) {
        parsedResponse = response.json()
          .then((json) => {
            response.__parsedResponseBody__ = json
            return response
          })
      }
      return (parsedResponse || response)
    })
    .then( () =>
    {
      console.log( 'DONE AUTHHHH  INNNNIITT' );
       authToken = response.token;
      console.log('Obtained Auth token', authToken);
    })

```

Which is still giving a `400` error: `{"errorCode":400,"description":"Fields are missing"}`

**Comment by krishnaIndia** [comment]
@joshuef, I just tried the same payload with the content type set from postman. Seems to be working fine. Can you please check the api once using the postman or curl?

**Comment by joshuef** [comment]
@krishnaIndia I've tested this on linux, and curl works 👍 

I'll have to wait till the evening to get back on my mac. But I'll test there and let you know! Thanks.

**Comment by joshuef** [comment]
seems like it was the node fetch implementation i was using. Tried via curl and other methods and I've got it working with isomorphic-fetch npm module. Thanks @krishnaIndia
