### ISSUE TITLE
Launcher Proceeds through Startup without User Input and Produces a Blank Window

### ISSUE THREAD

**Issue by fishertodd** [maidsafe/safe_launcher#191]
The Vault running on my OSX 10.9.5 desktop seems to be running like a champ with Routing Table size: 39 and 110762814 bytes at last count. Unfortunately, I cannot get the Launcher to work. Each time I start it, a new window appears. Then it asks for permissions, and sometimes, before I even have a chance to select "Allow", it advances to the password screen. Within about two seconds, the password screen then changes to just a blank screen and remains that way without ever giving me a chance to enter a password.

**Comment by Viv-Rajkumar** [comment]
Sorry about that. Not run into this personally.

> Each time I start it, a new window appears. Then it asks for permissions,

What permissions do you mean? do you have a screenshot?

One suggestion if its occurring repeatedly is, maybe 
- Close the "Launcher" and "Demo App".
- Open Activity Monitor
- Search for "Launcher"
<img width="702" alt="screen shot 2016-07-16 at 11 20 29" src="https://cloud.githubusercontent.com/assets/841795/16894217/cc9aa8f2-4b47-11e6-9c3e-5fe608893f1b.png">

- If you find any of the above entries, kill them so the list becomes empty. 
- Restart Launcher and see if it occurs again?

Just a guess if maybe a previous crash has left behind some processes which havent been terminated properly when exiting launcher App.

**Comment by fishertodd** [comment]
That did the trick and fixed my problem.  I had two processes running and I killed them.  Thank you for your assistance!


Todd

On 7/16/16 6:26 AM, Viv Rajkumar wrote:

Sorry about that. Not run into this personally.

Each time I start it, a new window appears. Then it asks for permissions,

What permissions do you mean? do you have a screenshot?

One suggestion if its occurring repeatedly is, maybe

  *   Close the "Launcher" and "Demo App".
  *   Open Activity Monitor
  *   Search for "Launcher"
[screen                  shot 2016-07-16 at 11 20 29]<https://cloud.githubusercontent.com/assets/841795/16894217/cc9aa8f2-4b47-11e6-9c3e-5fe608893f1b.png>

  *   If you find any of the above entries, kill them so the list becomes empty.

  *   Restart Launcher and see if it occurs again?

Just a guess if maybe a previous crash has left behind some processes which havent been terminated properly when exiting launcher App.
