### ISSUE TITLE
SAFE Launcher v0.6.0, reconnection issue

### ISSUE THREAD

**Issue by citan** [maidsafe/safe_launcher#192]
SAFE Launcher v0.6.0
OS : Win 10 64

--
Dear Maidsafe team,

It seems it is currently not possible to reconnect the launcher after the internet connection has been interrupted and reestablished. 

1. Start the launcher while the computer is connected to internet.
>As expected, the Launcher connects successfully

2. Disconnect the computer from internet. 
> After a few seconds, the launcher displays the message "Network Disconnected. Retrying in XXs"

3. Connect the computer to Internet

4. Wait a few seconds, and then try to reconnect the Launcher by pressing RETRY NOW. 
> No attempts (pressing retry or waiting) lead to a successful reconnection. The message "Network Disconnected. Retrying in XXs" keeps reappearing. The only way to reconnect is to close the Launcher and restart it.

The launcher's log, as well as screen captures can be found **[in this document](https://docs.google.com/document/d/10lgXE5s3G3j9vH_Prh3UDIw6Alc8nc1cmwuxdY65rF4/edit?usp=sharing)**

Best regards,

**Comment by daviddahl** [comment]
I am not able to connect to the MaidSafe network with 0.6.0 build for Mac OS X. Cannot create account, etc. The re-connection UI is permanently visible. Each retry fails. No logs in the logging UI or in mac console.

**Comment by krishnaIndia** [comment]
@daviddahl, test-6 is not live anymore. We are at present testing the [v0.7.1](https://github.com/maidsafe/safe_launcher/releases/tag/0.7.1) of launcher

You can read more from [this forum thread](https://forum.safenetwork.io/t/safe-network-test-7/10460/83)

@citan please do re-open the issue if the problem persists with [v0.7.1](https://github.com/maidsafe/safe_launcher/releases/tag/0.7.1).

Thanks for reporting the issue!

**Comment by daviddahl** [comment]
Thanks!
