### ISSUE TITLE
forum link in launcher 0.8 alpha 1 doesnt link to new current domain safenetforum.org

### ISSUE THREAD

**Issue by subscribernamegoeshere** [maidsafe/safe_launcher#232]
https://github.com/maidsafe/safe_launcher/releases/tag/0.8.0

link in about tab once running launcher 0.8 alpha 1 (tried x64 linux) does not apparently link or use the latest current safenetforum.org address but uses that .io something address from the past.

https://github.com/maidsafe/safe_launcher/blob/master/app/views/tab/help.html#L25

**Comment by subscribernamegoeshere** [comment]
https://github.com/maidsafe/safe_launcher/pull/233

**Comment by krishnaIndia** [comment]
Merged PR #233
