### ISSUE TITLE
v0.8.0-linux-x64 - FFI process terminated

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#235]
I've seen this now a few times in 0.8.0, though I can't be sure the cause, I had an impression of its being associated with connectivity issues - static on the line.. though that hasn't been so obviously an issue tonight; it might be a shorter disconnect that I didn't notice.. or something else entirely.

Anyhow, hoping that the snip of client and terminal will be useful.

What I saw was a pop-up error as below and on acknowledging that the terminal falls back to the prompt without further comment.

![screenshot at 2016-08-15 20 35 35](https://cloud.githubusercontent.com/assets/1708690/17677260/ee0c3682-6329-11e6-81ab-623256102f58.png)

[launcher-term.txt](https://github.com/maidsafe/safe_launcher/files/418818/launcher-term.txt)

[snip-client-log.txt](https://github.com/maidsafe/safe_launcher/files/418819/snip-client-log.txt)

**Comment by krishnaIndia** [comment]
Am able to reproduce this on windows too. Will fix it in the next update. 
Thanks again, @davidpbrown
