### ISSUE TITLE
POST /nfs/file says it creates empty file (API 0.5 documentation)

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_launcher#239]
Not sure where doc issues go so lodging this here. 

POST /nfs/file (https://maidsafe.readme.io/docs/nfsfile) still says "The API will only create a empty file in the directory specified in the file path" whereas it also says it stores data. I assume it will create if necessary. 

The API doc also doesn't specify whether or not you can write to an offset, and if so how.

**Comment by krishnaIndia** [comment]
Thanks @theWebalyst. The line is now corrected.

> The API doc also doesn't specify whether or not you can write to an offset, and if so how.

We don't have the option to partially mutate the file as the alpha release is using a Sequential Encryptor from self_encryptor crate. This can accept data only in a sequential order. The ability to provide offset while mutating a file will be implemented when the self_encryption library can accept offset value.

**Comment by theWebalyst** [comment]
Thanks @krishnaIndia I've only just started looking at the docs and looks like I'm finding a few things left over from the old API. What's the easiest way for me to supply these issues - should I register on readme.io and "suggest edits" or...?

**Comment by krishnaIndia** [comment]
@theWebalyst, `suggesting edits` in readme.io would be ideal. It would also help Francis to review and make the changes easily. Closing this issue for now. Please do re-open if there is anything more.

Thanks @theWebalyst
