### ISSUE TITLE
Build failure on 32-bit Win

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe_launcher#26]
It appears we have a lint warning triggering a build failure for 32-bit Windows only.

https://ci.appveyor.com/project/MaidSafe-QA/safe-launcher/build/1.0.106/job/prfmcxh24xxth6yk

This has been slipping through the net because we allow 32-bit builds to fail the AppVeyor tests due to the ongoing crypto issue.

**Comment by krishnaIndia** [comment]
This issue is no more related to the safe_launcher. In safe-core there is an open [issue](https://github.com/maidsafe/safe_core/issues/174), which discusses about the workaround for the same problem. If it is not relative, would be better to open an issue in safe_core.
