### ISSUE TITLE
package.json lists wrong version of react?

### ISSUE THREAD

**Issue by Abdisalan** [maidsafe/safe_launcher#304]
When I installed the project on new machine I get this error when I execute `npm run dev`

`ERROR in ./app/index.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/abdisalan/Documents/safe_launcher/app
[0]  @ ./app/index.js 1:312-343
`

Well, this error and about 100 other instances of it all over the app and they all reference `react/lib/ReactMount`.

The package.json file currently is set to `"react": "^15.3.0"`, and when I installed I got `react@15.4.0`.
I have another working instance of this repo and noticed it was using a older version of react, specifically `react@15.3.2`. I installed this version of react on the new machine and the app now works.

Has anyone else faced this issue? I haven't made a pull request because I want to first find out if we intentionally want to have the newest version of react.

**Comment by krishnaIndia** [comment]
Thanks @Abdisalan, will correct the version in `package.json` to use `~15.3.0`

**Comment by krishnaIndia** [comment]
@shankar2105 can we also check what are the changes in 15.4.0 which is breaking the present implementation?

**Comment by shankar2105** [comment]
Sure @krishnaIndia I'll do that.
