### ISSUE TITLE
issue on apt-get update and apt-get install safe-launcher

### ISSUE THREAD

**Issue by snydez** [maidsafe/safe_launcher#313]
Hi there
i try to install safe-launcher
when i **sudo apt-get update** i get this error

> W: Failed to fetch http://apt.maidsafe.net/repos/apt/debian/dists/jessie/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

and if try to continue to **apt-get install safe-launcher**, i get this message

> Reading state information... Done
> E: Unable to locate package safe-launcher

could you please advise?
thx

**Comment by frabrunelle** [comment]
Hi @snydez, it looks like you're trying to install SAFE Launcher on an ARM machine. The Alpha 1 network doesn't support ARM at the moment, so that's why you get this error.
