### ISSUE TITLE
Feature request: signing strings

### ISSUE THREAD

**Issue by davidkazlauskas** [maidsafe/safe_launcher#49]
Hi, I'm making an app and I want a way for user to express that he wants to use an app. I can't think of anything better than a digital signature. In short, I'd like to send a message to a safe launcher for signing, let's say with this json:

~~~~~~~
{
   "message": "<users public key> I_WANT_TO_USE_SO_AND_SO_APP",
   "myappsessiontoken": "<token>"
}
~~~~~~~

Then, I'd guess user would receive a message, saying "So and so app would like you to sign this text, blah blah blah"

User would click yes or no and I'd receive corresponding message.
~~~~~~~
{
    "message": "<the original>"
    "signature": "<libsodium detached signature as Base64>"
}
~~~~~~~

I'd like to receive signature as base 64 of the detached answer (without message) as specified here https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html .

I'm assuming that public user key (which is persistent from session to session) is libsodium public key (for signing) as base 64. Is that correct?

Could this feature be added?

**Comment by krishnaIndia** [comment]
Launcher is not a rust library any more. We have moved to electron. Thus closing this issue. You can check out the REST apis and let us know if anything that would like to get added to the APIs.
Thanks.
