### ISSUE TITLE
Unable to copy/paste in any field (Mac 10.11.3)

### ISSUE THREAD

**Issue by themorgantown** [maidsafe/safe_launcher#98]
Would like to be able to copy / paste within a password/keyword/ and pin field for the Safe Launcher (essential for strong passwords).

**Comment by ligthyear** [comment]
I can confirm this bug. Works on vagrant though (Debian, see #118 ). Appears to be [a fixed bug in electron](https://github.com/atom/electron/issues/2331), which lies in not having a proper menu. [Adding a default menu](https://github.com/atom/electron/blob/master/docs/api/menu.md) should fix this. I'll give it a try.

**Comment by ligthyear** [comment]
I can confirm this works when adding a menu. I'll create a PR for that.
