### ISSUE TITLE
eternally registering on certain new nodes? (digital ocen droplets overcrowded?)

### ISSUE THREAD

**Issue by subscribernamegoeshere** [maidsafe/safe_launcher#99]
I am giving the launcher a trial on a linux x64 and some winx64 machines. One winx64 machine registered itself pretty much immediately

The other winx64 machine on the same network is pending registration for many minutes now, and a linuxx64 machine is pending on a different network for tens of minutes already.

As far as I have briefly seen they are all connecting to different ipv4 addresses of those digial ocean or whatever droplets you guys are currently using.

tcp 5483 on remote target is established to ipv4 on all of my testing machines, but still only the one win machine managed to go to the normal launcher gui, the other two are still animating and registering.

Are the digital ocean droplets independant from each other, or are all of these digital ocean ipv4 addresses already forming a single maidsafe group or entity regarding this testnet stage?

Should I wait longer or just re-run the launchers on the two affected pending systems?

**Comment by dirvine** [comment]
If you just rerun the launcher then it should be fine. Thx for testing with us.

**Comment by subscribernamegoeshere** [comment]
the .12.6 is pending and so is the .13.107
the successful one was/is with the .12.173

Probably a fallback, round-robin or multiple connection attempts, loops etc, ought to be added for robustness. Thanks.

**Comment by subscribernamegoeshere** [comment]
one more via initially 13.166 connected but then used some more droplets or ip addreses. took maybe ten seconds or so, then successfully joined. now I have the linux node left to try.

**Comment by subscribernamegoeshere** [comment]
Yay. linux created account via .12.245, then .12.239, and then landed at or even added .13.93

**Comment by krishnaIndia** [comment]
Please do try the [version 0.7.1](https://github.com/maidsafe/safe_launcher/releases/tag/0.7.1) and open this issue again if you have the same problem.

Thanks @subscribernamegoeshere
